from fastapi import APIRouter
from fastapi.responses import StreamingResponse, JSONResponse
from data.profile_data import PROFILE
import io, datetime

router = APIRouter()


@router.get("/profile")
async def get_profile():
    return {
        "meta": PROFILE["meta"],
        "about": PROFILE["about"],
        "about_system": PROFILE["about_system"],
        "skills": PROFILE["skills"],
        "projects": PROFILE["projects"],
        "experience": PROFILE["experience"],
        "education": PROFILE["education"],
    }


@router.get("/resume")
async def download_resume():
    """Generate a Mitre CVE-style security advisory as a downloadable Markdown file."""
    meta = PROFILE["meta"]
    skills = PROFILE["skills"]
    projects = PROFILE["projects"]
    edu = PROFILE["education"]
    now = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")

    skill_block = "\n".join(
        f"  - **{s['name']}** — Proficiency: {s['level']}%  "
        f"[{'█' * (s['level']//10)}{'░' * (10 - s['level']//10)}]"
        for s in skills
    )

    edu_block = "\n".join(
        f"  - **{e['degree']}** · {e['institution']}, {e['location']}  ({e['year']}) — _{e['status']}_"
        for e in edu
    )

    proj_block = "\n\n".join(
        f"#### {p['title']}\n"
        f"  - **Status**: {p['status']}\n"
        f"  - **Summary**: {p['description']}\n"
        f"  - **Technology Vector**: {', '.join(p['tech'])}\n"
        f"  - **Measured Impact**: {p['impact']}\n"
        f"  - **Node IP**: `{p['ip']}`\n"
        f"  - **Repository**: {p['github']}"
        for p in projects
    )

    content = f"""# MITRE CVE SECURITY ADVISORY
## CVE-2026-CORE · SEVERITY: CRITICAL

---

**Published**: {now}
**Modified**: {now}
**CVE ID**: CVE-2026-CORE
**CVSS v3.1 Score**: 10.0 (CRITICAL)
**CVSS Vector**: AV:N/AC:L/PR:N/UI:R/S:C/C:H/I:H/A:H

---

## 1. VULNERABILITY SUMMARY

**Vulnerability Target**: Tech Talent Scarcity & Structural Engineering Inefficiencies
**Affected Domain**: Enterprise software development, full-stack engineering, cyber security research
**Remediation**: Immediate engagement with subject required.

---

## 2. SUBJECT IDENTITY

| Field         | Value                                |
|---------------|--------------------------------------|
| Legal Name    | {meta['name']}                       |
| Alias         | {meta['alias']}                      |
| Location      | {meta['location']}                   |
| Email         | {meta['email']}                      |
| GitHub        | {meta['github']}                     |
| Instagram     | {meta['instagram']}                  |

---

## 3. EXPLOIT VECTOR — CAPABILITY PAYLOAD

The following technical capabilities have been independently verified and are classified
as active exploit payloads against organizational inefficiencies:

{skill_block}

---

## 4. PROOF OF CONCEPT (PoC)

### Deployed Systems

{proj_block}

---

## 5. INSTITUTIONAL VALIDATION

{edu_block}

---

## 6. SYSTEM CONTEXT

{PROFILE['about_system']}

---

## 7. RECOMMENDED REMEDIATION

1. Initiate contact at `{meta['email']}` with subject: `[CVE-2026-CORE] Remediation`
2. Schedule technical interview to validate exploit payloads
3. Issue offer letter to patch vulnerability within 30 days
4. **FAILURE TO REMEDIATE** will result in competitor organizations acquiring this asset

---

## 8. REFERENCES

- GitHub: {meta['github']}
- Project: Garment Flow ERP — garment manufacturing lifecycle management
- Project: Khaja Ghar — multi-vendor food delivery platform

---

*This document is structured as a Mitre CVE advisory for creative and demonstrative purposes.*
*Generated by baakaa portfolio system — {now}*
"""

    buf = io.BytesIO(content.encode("utf-8"))
    buf.seek(0)
    return StreamingResponse(
        buf,
        media_type="text/markdown",
        headers={"Content-Disposition": "attachment; filename=CVE-2026-CORE-baakaa.md"},
    )
